# Makefile for OpenGL/GLUT programs.

# Author: John M. Weiss, Ph.D.
# Written Fall 2016 for CSC433/533 Computer Graphics.

# Usage:  make target1 target2 ...

#-----------------------------------------------------------------------

# GNU C/C++ compiler and linker:
CC = gcc
CXX = g++
LINK = g++
NVLINK = nvcc
NVCC = nvcc

# Turn on optimization and warnings (add -g for debugging with gdb):
# CPPFLAGS = 		# preprocessor flags
CFLAGS = -O #-Wall -Wextra
CXXFLAGS = -O -std=c++11 #-Wall -Wextra
NVCCFLAGS = -O -std=c++11 #-Wall -Wextra

# OpenGL/Mesa libraries for Linux:
GL_LIBS = -lglut -lGLU -lGL -lm

# OpenGL libraries for Windows (MinGW):
# GL_LIBS = -lfreeglut -lglu32 -lopengl32
# GL_LIBS = -lglut32 -lglu32 -lopengl32

# OpenGL libraries for Windows (MSVS):
# GL_LIBS = opengl32.lib glu32.lib freeglut.lib
# GL_LIBS = opengl32.lib glu32.lib glut32.lib

#-----------------------------------------------------------------------

# MAKE allows the use of "wildcards", to make writing compilation instructions
# a bit easier. GNU make uses $@ for the target and $^ for the dependencies.

all:    mandelbrot

# specific targets
mandelbrot:	fractalview.o calculations.o calculationscuda.o common.o colors.o
	$(NVLINK) -o $@ $^ $(GL_LIBS) -lcuda -lcudart

calculationscuda.o:
	nvcc -c -std=c++11 -arch=sm_20 calculationscuda.cu -g

# generic C and C++ targets for OpenGL programs consisting of only one file
# type "make filename" (no extension) to build
.c:
	$(CC) -o $@ $@.c $(CFLAGS) $(GL_LIBS)

.cpp:
	$(CXX) -o $@ $@.cpp $(CXXFLAGS) $(GL_LIBS)

.cu:
	$(NVCC) -o $@ $@.cu $(NVCCFLAGS) $(GL_LIBS)

# utility targets
clean:
	rm -f *.o *~ *.gch core
